default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: harman
  password: admin  
  timeout: 5000

development: 
  <<: *default
  database: my_database_development

test: 
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: my_database_production
